services:
  catalogodsr_v5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalogodsr-app-v5
    restart: always
    command: npm run dev -- --host 0.0.0.0 --port 8106
    ports:
      - "8106:8106"
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://159.223.161.112:8106}
